---
- name: Installing MS office
  hosts: 3.140.229.8
  become: runas
  tasks:
    - name: check to see if msoffice is installed
      win_stat: path='C:\Program Files\Setup64.exe'
      register: msoffice_installed
    - name: Download MS Office 2019
      win_get_url:
        url: 'https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/ProPlus2019Retail.img'
        dest: 'C:\MSOffice2019'
      when: not msoffice_installed.stat.exists
    - name: Install MS Office 2019
      win_disk_image:
        image_path: 'C:\MSOffice2019\ProPlus2019Retail.img'
        state: present
    - name: Running the Installer
      win_shell: 'D:\Office\Setup64.exe'
      when: not msoffice_installed.stat.exists
    - name: Setting the Product Key
      win_command: 'cscript ospp.vbs /inpkey:99KRX-3NFXF-BGYX3-W44PQ-TCRXB'
      args:
        chdir: 'C:\Program Files\Microsoft Office\Office16'
