---
- name: Installing MS Visio
  hosts: 3.140.229.8
  become: runas
  tasks:
    - name: Check to see if msvisio is installed
      win_stat: path='C:\Program Files\Setup.exe'
      register: msvisio_installed
    - name: Download MS Visio 2019
      win_get_url:
        url: 'https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/VisioPro2019Retail.img'
        dest: 'C:\MSVisio2019'
      when: not msvisio_installed.stat.exists
    - name: Install MS Visio 2019
      community.windows.win_disk_image:
        image_path: 'C:\MSVisio2019\VisioPro2019Retail.img'
        state: present
    - name: Running the Installer
      win_shell: 'D:\Office\Setup64.exe'
      when: not msvisio_installed.stat.exists
    - name: Setting the Product Key
      win_command: 'cscript ospp.vbs /inpkey:DVHYN-27KHH-KXH8T-84DF2-YKP79'
      args:
        chdir: 'C:\Program Files\Microsoft Office\Office16'
