---
- name: Installing MS Visio
  hosts: 3.140.229.8
  become: runas
  force_handlers: yes
  ignore_errors: yes
  tasks:
    - name: Check to see if msvisio is installed
      win_stat: path='C:\Program Files\Setup.exe'
      register: msvisio_installed
    - name: Download MS Visio 2019
      win_get_url:
        url: 'https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/VisioPro2019Retail.img'
        dest: 'C:\Users\Administrator\Downloads'
      when: not msvisio_installed.stat.exists
    - name: Install MS Visio 2019
      community.windows.win_disk_image:
        image_path: 'C:\Users\Administrator\Downloads\VisioPro2019Retail.img'
        state: present
    - name: Running the Installer
      win_shell: 'D:\Office\Setup64.exe'
      when: not msvisio_installed.stat.exists
      notify: show_msg1
    - name: Running the Installer
      win_shell: 'E:\Office\Setup64.exe'
      when: not msvisio_installed.stat.exists
      notify: show_msg2
    - name: Running the Installer
      win_shell: 'F:\Office\Setup64.exe'
      when: not msvisio_installed.stat.exists
      notify: show_msg3
    - name: Running the Installer
      win_shell: 'G:\Office\Setup64.exe'
      when: not msvisio_installed.stat.exists
      notify: show_msg4
    - name: Running the Installer
      win_shell: 'H:\Office\Setup64.exe'
      when: not msvisio_installed.stat.exists
      notify: show_msg5
    - name: Setting the Product Key
      win_command: 'cscript ospp.vbs /inpkey:DVHYN-27KHH-KXH8T-84DF2-YKP79'
      args:
        chdir: 'C:\Program Files\Microsoft Office\Office16'
    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: smtp.gmail.com
        port: 587
        username: imssdevops@gmail.com
        password: xszpyxymsfhgynbp
        to: imssdevops@gmail.com
        subject: Ansible-report
        body: successfully installed MS Visio 2019.
      delegate_to: localhost
  handlers:
    - name: show_msg1
      debug:
        msg: "Visio installed in drive D"
    - name: show_msg2
      debug:
        msg: "Visio installed in drive E"
    - name: show_msg3
      debug:
        msg: "Visio installed in drive F"
    - name: show_msg4
      debug:
        msg: "Visio installed in drive G"
    - name: show_msg5
      debug:
        msg: "Visio installed in drive H"
